FROM python:3.10.5-alpine3.16

RUN pip install -U py-cord
RUN pip install python-dotenv
RUN pip install sqlalchemy[asyncio] sqlalchemy-utils
RUN pip install alembic asyncpg psycopg2-binary
RUN pip install python-dateutil pytz
RUN pip install pycord18n

WORKDIR /bot

ADD src/alembic.ini ./alembic.ini
ADD src/gci.py ./gci.py
ADD src/database.py ./database.py
ADD src/exceptions.py ./exceptions.py
ADD src/main.py ./main.py
ADD src/models.py ./models.py
ADD src/logging.conf ./logging.conf

ADD src/cogs ./cogs
ADD src/alembic ./alembic
ADD src/db_util ./db_util
ADD src/data ./data
ADD src/ui ./ui
ADD src/lang ./lang

CMD [ "python3", "main.py" ]