FROM python:3.10.5-alpine3.16

RUN pip install -U py-cord
RUN pip install python-dotenv
RUN pip install sqlalchemy[asyncio] sqlalchemy-utils
RUN pip install alembic asyncpg
RUN pip install python-dateutil pytz

WORKDIR /bot

ADD src/alembic.ini ./alembic.ini
ADD src/bci.py ./bci.py
ADD src/database.py ./database.py
ADD src/exceptions.py ./exceptions.py
ADD src/main.py ./main.py
ADD src/models.py ./models.py

ADD src/cogs ./cogs
ADD src/alembic ./alembic
ADD src/db_util ./db_util
ADD src/data ./data

CMD [ "python3", "main.py" ]