services:
  bot:
    build:
      context: ..
      dockerfile: infra/Dockerfile-bot
    restart: always
    env_file: .env
    ports:
      - 443:443
      - 80:80
    depends_on:
      - bot-database

  bot-database:
    image: postgres:14.3-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - bot_db_volume_pg:/data

volumes:
  bot_db_volume_pg: