FROM python:3.10.5-alpine3.16

COPY infra/requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

WORKDIR /bot

ADD src/alembic.ini ./alembic.ini
ADD src/gci.py ./gci.py
ADD src/database.py ./database.py
ADD src/exceptions.py ./exceptions.py
ADD src/main.py ./main.py
ADD src/models.py ./models.py
ADD src/logging.conf ./logging.conf
ADD src/gsheet_helpers.py ./gsheet_helpers.py

ADD src/cogs ./cogs
ADD src/alembic ./alembic
ADD src/db_util ./db_util
ADD src/gsheet ./gsheet
ADD src/data ./data
ADD src/ui ./ui
ADD src/lang ./lang

CMD [ "python3", "main.py" ]