"""add loot count field

Revision ID: 0a811bca3942
Revises: be975d450f27
Create Date: 2022-08-23 15:58:44.823036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a811bca3942'
down_revision = 'be975d450f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loot', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loot', 'count')
    # ### end Alembic commands ###
