"""change is_main to main_status

Revision ID: 0c7ff4f28c79
Revises: c7b37856201f
Create Date: 2022-11-10 00:39:54.560523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7ff4f28c79'
down_revision = 'c7b37856201f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE mainstatusenum AS ENUM ('MAIN', 'REROLL', 'OTHER')")
    enum = sa.Enum('MAIN', 'REROLL', 'OTHER', name='mainstatusenum')
    op.add_column('character', sa.Column('main_status', enum, nullable=True))
    op.execute("UPDATE character SET main_status = 'OTHER'")
    op.execute("UPDATE character SET main_status = 'MAIN' WHERE is_main")
    op.alter_column('character', sa.Column('main_status', nullable=False))
    op.drop_column('character', 'is_main')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('character', 'main_status')
    op.execute("DROP TYPE mainstatusenum")
    # ### end Alembic commands ###
