"""add settings table

Revision ID: 12895b7c561c
Revises: 
Create Date: 2022-08-22 13:52:00.775271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12895b7c561c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('id_guild', sa.String(length=22), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_guild')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_settings')
    # ### end Alembic commands ###
