"""no count for loot

Revision ID: 1df78b5885ed
Revises: a4aab942bc52
Create Date: 2022-09-26 08:00:16.548098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1df78b5885ed'
down_revision = 'a4aab942bc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE loot DROP CONSTRAINT loot_pkey CASCADE')
    op.add_column('loot', sa.Column('id', sa.Integer(), nullable=False))
    op.execute("CREATE SEQUENCE loot_id_seq AS integer START 1 OWNED BY loot.id")
    op.alter_column('loot', 'id', server_default=sa.text("nextval('loot_id_seq'::regclass)"))
    op.create_primary_key('loot_pkey', 'loot', ['id'])
    op.drop_column('loot', 'count')
    op.drop_column('loot', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loot', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('loot', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute('ALTER TABLE loot DROP CONSTRAINT loot_pkey CASCADE')
    op.drop_column('loot', 'id')
    op.create_primary_key('loot_pkey', 'loot', ['id_item', 'id_character'])
    # ### end Alembic commands ###
