"""add_to_primkey

Revision ID: 20a38834f572
Revises: 56ad2ac27e22
Create Date: 2022-07-27 22:05:32.858210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20a38834f572'
down_revision = '56ad2ac27e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'raid_size',
               existing_type=postgresql.ENUM('RAID10', 'RAID25', name='raidsizeenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'raid_size',
               existing_type=postgresql.ENUM('RAID10', 'RAID25', name='raidsizeenum'),
               nullable=True)
    # ### end Alembic commands ###
