"""add open at field in raid

Revision ID: 235b06ce7b6d
Revises: b770e46c7bb7
Create Date: 2022-10-05 06:28:48.446704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235b06ce7b6d'
down_revision = 'b770e46c7bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raid', sa.Column('open_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE raid SET open_at = NOW()")
    op.alter_column("raid", "open_at", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raid', 'open_at')
    # ### end Alembic commands ###
