"""add cheer message

Revision ID: 4e36dcc040e6
Revises: 12895b7c561c
Create Date: 2022-08-22 19:11:30.409985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e36dcc040e6'
down_revision = '12895b7c561c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('cheer_message', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'cheer_message')
    # ### end Alembic commands ###
