"""added_raid_size

Revision ID: 56ad2ac27e22
Revises: b7bc69cda2bd
Create Date: 2022-07-27 14:40:27.276289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from db_util.wow_data import RaidSizeEnum, enum_names


# revision identifiers, used by Alembic.
revision = '56ad2ac27e22'
down_revision = 'b7bc69cda2bd'
branch_labels = None
depends_on = None


def upgrade():
    col_data = [("raid_size", "raidsizeenum", RaidSizeEnum)]
    for col, name, cls in col_data:
        enum = postgresql.ENUM(*enum_names(cls), name=name)
        enum.create(op.get_bind())
        op.add_column('attendance', sa.Column(col, sa.Enum(*enum_names(cls), name=name), nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'raid_size')
    op.execute("DROP TYPE raidsizeenum;")