"""add prio role in settings

Revision ID: 6222825ed1c8
Revises: 235b06ce7b6d
Create Date: 2022-10-10 11:17:36.368281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6222825ed1c8'
down_revision = '235b06ce7b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('id_prio_role', sa.String(length=22), nullable=True))
    op.alter_column('raid', 'open_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raid', 'open_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('guild_settings', 'id_prio_role')
    # ### end Alembic commands ###
