"""add dkp flag in loot table

Revision ID: 71237a836be1
Revises: a31e7ec90acc
Create Date: 2022-09-25 09:38:08.134920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71237a836be1'
down_revision = 'a31e7ec90acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loot', sa.Column('in_dkp', sa.Boolean(), nullable=True, default=False))
    op.execute("UPDATE loot SET in_dkp = false")
    op.alter_column('loot', 'in_dkp', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loot', 'in_dkp')
    # ### end Alembic commands ###
