"""add guild event column

Revision ID: a4aab942bc52
Revises: 71237a836be1
Create Date: 2022-09-25 21:12:07.350204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4aab942bc52'
down_revision = '71237a836be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('is_guild_event', sa.Boolean(), nullable=True))
    op.execute("UPDATE attendance SET is_guild_event = false")
    op.alter_column('attendance', 'is_guild_event', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'is_guild_event')
    # ### end Alembic commands ###
