"""Added role and class columns to character

Revision ID: b7bc69cda2bd
Revises: 
Create Date: 2022-07-27 12:33:44.861879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from db_util.wow_data import ClassEnum, RoleEnum, enum_names


# revision identifiers, used by Alembic.
revision = 'b7bc69cda2bd'
down_revision = None
branch_labels = None
depends_on = None

    
def upgrade():
    col_data = [("role", "roleenum", RoleEnum), ("character_class", "classenum", ClassEnum)]
    for col, name, cls in col_data:
        enum = postgresql.ENUM(*enum_names(cls), name=name)
        enum.create(op.get_bind())
        op.add_column('character', sa.Column(col, sa.Enum(*enum_names(cls), name=name), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'character_class')
    op.drop_column('character', 'role')
    op.execute("DROP TYPE roleenum;")
    op.execute("DROP TYPE classenum;")
    # ### end Alembic commands ###
