"""add onupdate/default for datetimes

Revision ID: be975d450f27
Revises: 4e36dcc040e6
Create Date: 2022-08-23 15:55:59.193829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be975d450f27'
down_revision = '4e36dcc040e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('character', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('loot', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loot', 'updated_at')
    op.drop_column('character', 'updated_at')
    op.drop_column('attendance', 'updated_at')
    # ### end Alembic commands ###
