"""add_ghsheet_id

Revision ID: c357bcb06172
Revises: 0a811bca3942
Create Date: 2022-08-27 15:19:44.711005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c357bcb06172'
down_revision = '0a811bca3942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('id_export_gsheet', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'id_export_gsheet')
    # ### end Alembic commands ###
