"""add_dkp_flag_in_attendance_table

Revision ID: c853e6725571
Revises: 0c7ff4f28c79
Create Date: 2023-06-22 20:21:58.730638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c853e6725571'
down_revision = '0c7ff4f28c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('in_dkp', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'in_dkp')
    # ### end Alembic commands ###
