ITEM_CLASS = {
  0:"Consumable",
  1:"Container",
  2:"Weapon",
  3:"Gem",
  4:"Armor",
  5:"Reagent",
  6:"Projectile",
  7:"Trade Goods",
  8:"Generic(OBSOLETE)",
  9:"Recipe",
  10:"Money(OBSOLETE)",
  11:"Quiver",
  12:"Quest",
  13:"Key",
  14:"Permanent(OBSOLETE)",
  15:"Miscellaneous",
  16:"Glyph"
}

ITEM_QUALITY = {
  0:("Grey","Poor"),
  1:("White","Common"),
  2:("Green","Uncommon"),
  3:("Blue","Rare"),
  4:("Purple","Epic"),
  5:("Orange","Legendary"),
  6:("Red","Artifact"),
  7:("Gold","Bind to Account")
}

ITEM_INVENTORY_TYPE = {
  0:"Non equipable",
  1:"Head",
  2:"Neck",
  3:"Shoulder",
  4:"Shirt",
  5:"Chest",
  6:"Waist",
  7:"Legs",
  8:"Feet",
  9:"Wrists",
  10:"Hands",
  11:"Finger",
  12:"Trinket",
  13:"Weapon",
  14:"Shield",
  15:"Ranged (Bows)",
  16:"Back",
  17:"Two-Hand",
  18:"Bag",
  19:"Tabard",
  20:"Robe",
  21:"Main hand",
  22:"Off hand",
  23:"Holdable (Tome)",
  24:"Ammo",
  25:"Thrown",
  26:"Ranged right (Wands, Guns)",
  27:"Quiver",
  28:"Relic"
}

STATS_TYPE = {
  0: "ITEM_MOD_MANA",
  1: "ITEM_MOD_HEALTH",
  3: "ITEM_MOD_AGILITY",
  4: "ITEM_MOD_STRENGTH",
  5: "ITEM_MOD_INTELLECT",
  6: "ITEM_MOD_SPIRIT",
  7: "ITEM_MOD_STAMINA",
  12: "ITEM_MOD_DEFENSE_SKILL_RATING",
  13: "ITEM_MOD_DODGE_RATING",
  14: "ITEM_MOD_PARRY_RATING",
  15: "ITEM_MOD_BLOCK_RATING",
  16: "ITEM_MOD_HIT_MELEE_RATING",
  17: "ITEM_MOD_HIT_RANGED_RATING",
  18: "ITEM_MOD_HIT_SPELL_RATING",
  19: "ITEM_MOD_CRIT_MELEE_RATING",
  20: "ITEM_MOD_CRIT_RANGED_RATING",
  21: "ITEM_MOD_CRIT_SPELL_RATING",
  22: "ITEM_MOD_HIT_TAKEN_MELEE_RATING",
  23: "ITEM_MOD_HIT_TAKEN_RANGED_RATING",
  24: "ITEM_MOD_HIT_TAKEN_SPELL_RATING",
  25: "ITEM_MOD_CRIT_TAKEN_MELEE_RATING",
  26: "ITEM_MOD_CRIT_TAKEN_RANGED_RATING",
  27: "ITEM_MOD_CRIT_TAKEN_SPELL_RATING",
  28: "ITEM_MOD_HASTE_MELEE_RATING",
  29: "ITEM_MOD_HASTE_RANGED_RATING",
  30: "ITEM_MOD_HASTE_SPELL_RATING",
  31: "ITEM_MOD_HIT_RATING",
  32: "ITEM_MOD_CRIT_RATING",
  33: "ITEM_MOD_HIT_TAKEN_RATING",
  34: "ITEM_MOD_CRIT_TAKEN_RATING",
  35: "ITEM_MOD_RESILIENCE_RATING",
  36: "ITEM_MOD_HASTE_RATING",
  37: "ITEM_MOD_EXPERTISE_RATING",
  38: "ITEM_MOD_ATTACK_POWER",
  39: "ITEM_MOD_RANGED_ATTACK_POWER",
  40: "ITEM_MOD_FERAL_ATTACK_POWER",
  41: "ITEM_MOD_SPELL_HEALING_DONE",
  42: "ITEM_MOD_SPELL_DAMAGE_DONE",
  43: "ITEM_MOD_MANA_REGENERATION",
  44: "ITEM_MOD_ARMOR_PENETRATION_RATING",
  45: "ITEM_MOD_SPELL_POWER",
  46: "ITEM_MOD_HEALTH_REGEN",
  47: "ITEM_MOD_SPELL_PENETRATION",
  48: "ITEM_MOD_BLOCK_VALUE",
}
